In [44]:
from __future__ import annotations
from typing import Tuple
import pandas as pd
import pickle
import numpy as np
from scipy import spatial
import sklearn as skl
import os
import json
import fasttext
import fasttext.util
import string
import math
import seaborn as sns

In [56]:
from sklearn.cluster import AffinityPropagation 
from sklearn.cluster import KMeans

In [6]:
v1 = pickle.load(open('../data/word_vec_binary.bin', 'br'))
v2 = pickle.load(open('../data/country_vect_dict.bin', 'br'))
v3 = pickle.load(open('../data/food_tags_vect_dict.bin', 'br'))

In [61]:
apClass = AffinityPropagation(max_iter=1000,random_state=0)
kClass = KMeans(max_iter=1000, random_state=0, n_clusters=4)

In [62]:
df = pd.DataFrame.from_dict(v1, orient='index')

In [63]:
apClass.labels_ = df.index

In [64]:
vects = np.array(df.to_numpy())

In [65]:
modelAf = apClass.fit(vects)
modelK = kClass.fit(vects)

In [66]:
modelK.cluster_centers_

array([[-1.37950878,  0.43500578, -1.14144024, ...,  2.28503532,
         1.53601639,  0.52501636],
       [-1.05204174,  0.08113313, -0.57740587, ...,  1.68440623,
         0.90041645,  0.49912414],
       [-1.76636703,  0.03357431, -0.89117809, ...,  2.54565447,
         1.32004133,  0.72510326],
       [-1.03943714,  0.13236428, -1.0497449 , ...,  1.94355038,
         1.24022276,  0.41924492]])

In [67]:
modelK.labels_

array([3, 0, 2, ..., 1, 1, 3], dtype=int32)

In [71]:
modelK.predict(vects[0].reshape(-1,300))

array([3], dtype=int32)